<a href="https://colab.research.google.com/github/RagaSandhiya05/LLM-From-Scratch/blob/main/03_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**WORD EMBEDDINGS**

**Import PyTorch**

In [1]:
import torch
import torch.nn as nn
print("PyTorch Version : " , torch.__version__)

PyTorch Version :  2.11.0+cpu


**Create Sample Vocabulary**

In [2]:
words = [
    "artificial" ,
    "intelligence" ,
    "is" ,
    "changing" ,
    "the" ,
    "world" ,
    "large" ,
    "language" ,
    "models" ,
    "chatgpt"
]
word_to_id = {}
for i , word in enumerate(words) :
  word_to_id[word] = i
print(word_to_id)

{'artificial': 0, 'intelligence': 1, 'is': 2, 'changing': 3, 'the': 4, 'world': 5, 'large': 6, 'language': 7, 'models': 8, 'chatgpt': 9}


**Create Embedding Layer**

In [4]:
vocab_size = len(words)
embedding_dimension = 8
embedding = nn.Embedding(vocab_size , embedding_dimension)
print(embedding)

Embedding(10, 8)


**Convert Word into ID**

In [5]:
word = "language"
word_id = torch.tensor([word_to_id[word]])
print("Word : " , word)
print("ID : " , word_id.item())

Word :  language
ID :  7


**Get Embedding Vector**

In [6]:
vector = embedding(word_id)
print("Embedding Vector:\n")
print(vector)

Embedding Vector:

tensor([[-0.6103,  0.6521,  1.0267,  0.4753,  3.3744,  1.0211,  0.0907,  1.9818]],
       grad_fn=<EmbeddingBackward0>)


**Check Vector Shape**

In [7]:
print("Shape : " , vector.shape)

Shape :  torch.Size([1, 8])


**Convert Multiple Words**

In [8]:
sentence = [
    "artificial" ,
    "intelligence" ,
    "is" ,
    "changing" ,
    "the" ,
    "world"
]
ids = []
for word in sentence :
  ids.append(word_to_id[word])
ids = torch.tensor(ids)
print(ids)

tensor([0, 1, 2, 3, 4, 5])


**Get Sentence Embeddings**

In [10]:
sentence_vectors = embedding(ids)
print(sentence_vectors)

tensor([[ 1.0141, -1.1546, -0.1500,  0.5086, -0.2603,  0.0243,  1.6482, -1.4404],
        [ 0.0626,  0.6918, -0.0689,  1.1961, -0.3837,  0.4042, -1.6606, -0.0825],
        [-2.1187,  0.1235, -0.5437, -0.4070,  0.7914,  0.8631,  1.1792,  0.4850],
        [ 0.5747, -0.2417,  0.3741,  0.4314,  1.9598, -1.2856, -0.9456, -0.9450],
        [-0.5457, -0.3719, -0.5280, -0.8156, -2.4130,  1.9448, -1.5937,  1.0953],
        [-1.3242,  0.3664, -1.1028, -0.5231, -0.4267,  0.1062, -0.5491,  0.5215]],
       grad_fn=<EmbeddingBackward0>)


**Print Every Word With its Vector**

In [14]:
for word in sentence :
  idx = torch.tensor([word_to_id[word]])
  vector = embedding(idx)
  print("=" * 40)
  print("Word : " , word)
  print("Vector : ")
  print(vector)

Word :  artificial
Vector : 
tensor([[ 1.0141, -1.1546, -0.1500,  0.5086, -0.2603,  0.0243,  1.6482, -1.4404]],
       grad_fn=<EmbeddingBackward0>)
Word :  intelligence
Vector : 
tensor([[ 0.0626,  0.6918, -0.0689,  1.1961, -0.3837,  0.4042, -1.6606, -0.0825]],
       grad_fn=<EmbeddingBackward0>)
Word :  is
Vector : 
tensor([[-2.1187,  0.1235, -0.5437, -0.4070,  0.7914,  0.8631,  1.1792,  0.4850]],
       grad_fn=<EmbeddingBackward0>)
Word :  changing
Vector : 
tensor([[ 0.5747, -0.2417,  0.3741,  0.4314,  1.9598, -1.2856, -0.9456, -0.9450]],
       grad_fn=<EmbeddingBackward0>)
Word :  the
Vector : 
tensor([[-0.5457, -0.3719, -0.5280, -0.8156, -2.4130,  1.9448, -1.5937,  1.0953]],
       grad_fn=<EmbeddingBackward0>)
Word :  world
Vector : 
tensor([[-1.3242,  0.3664, -1.1028, -0.5231, -0.4267,  0.1062, -0.5491,  0.5215]],
       grad_fn=<EmbeddingBackward0>)


**Vocabulary Size & Embedding Size**

In [15]:
print("Vocabulary Size : " , vocab_size)
print("Embedding Dimension : " , embedding_dimension)
print("Embedding Weight Shape : " , embedding.weight.shape)

Vocabulary Size :  10
Embedding Dimension :  8
Embedding Weight Shape :  torch.Size([10, 8])


**Display All Embeddings**

In [17]:
print("All Learned Embeddings")
print(embedding.weight)

All Learned Embeddings
Parameter containing:
tensor([[ 1.0141e+00, -1.1546e+00, -1.5002e-01,  5.0861e-01, -2.6029e-01,
          2.4254e-02,  1.6482e+00, -1.4404e+00],
        [ 6.2567e-02,  6.9181e-01, -6.8940e-02,  1.1961e+00, -3.8375e-01,
          4.0424e-01, -1.6606e+00, -8.2466e-02],
        [-2.1187e+00,  1.2347e-01, -5.4372e-01, -4.0701e-01,  7.9145e-01,
          8.6311e-01,  1.1792e+00,  4.8500e-01],
        [ 5.7475e-01, -2.4166e-01,  3.7408e-01,  4.3138e-01,  1.9598e+00,
         -1.2856e+00, -9.4556e-01, -9.4497e-01],
        [-5.4569e-01, -3.7186e-01, -5.2802e-01, -8.1561e-01, -2.4130e+00,
          1.9448e+00, -1.5937e+00,  1.0953e+00],
        [-1.3242e+00,  3.6641e-01, -1.1028e+00, -5.2312e-01, -4.2673e-01,
          1.0617e-01, -5.4913e-01,  5.2148e-01],
        [-1.1995e+00,  2.3032e-02,  3.4636e-01, -8.5090e-01,  9.7006e-01,
         -6.4366e-01, -1.2951e+00, -9.7762e-01],
        [-6.1035e-01,  6.5205e-01,  1.0267e+00,  4.7525e-01,  3.3744e+00,
          1.0211e+00