<a href="https://colab.research.google.com/github/RagaSandhiya05/LLM-From-Scratch/blob/main/08_Multi_Head_Attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MULTI-HEAD ATTENTION**

**Import Libraries**

In [1]:
import torch
import torch.nn.functional as F
torch.manual_seed(42)
print("PyTorch Version : " , torch.__version__)

PyTorch Version :  2.11.0+cpu


**Sample Embeddings**

In [2]:
tokens = ["I" , "love" , "Python"]
embeddings = torch.tensor([
    [1.0 , 0.5 , 0.2 , 0.1] ,
    [0.8 , 1.0 , 0.4 , 0.3] ,
    [0.2 , 0.1 , 1.0 , 0.9]
])
print("Tokens : ")
print(tokens)

print("'\nEmbeddings : ")
print(embeddings)

Tokens : 
['I', 'love', 'Python']
'
Embeddings : 
tensor([[1.0000, 0.5000, 0.2000, 0.1000],
        [0.8000, 1.0000, 0.4000, 0.3000],
        [0.2000, 0.1000, 1.0000, 0.9000]])


**Self-Attention Function**

In [6]:
def self_attention(embeddings) :
  embedding_dim = embeddings.shape[1]
  Wq = torch.randn(embedding_dim , embedding_dim)
  Wk = torch.randn(embedding_dim , embedding_dim)
  Wv = torch.randn(embedding_dim , embedding_dim)

  Q = embeddings @ Wq
  K = embeddings @ Wk
  V = embeddings @ Wv

  scores = Q @ K.T

  scores = scores / (embedding_dim ** 0.5)

  attention = F.softmax(scores , dim = -1)

  context = attention @ V
  return context

**Head 1**

In [7]:
head1 = self_attention(embeddings)
print("Head 1 Output :\n")
print(head1)

Head 1 Output :

tensor([[ 1.7690,  1.9718, -1.7850,  0.0694],
        [ 1.5779,  1.8138, -2.0367,  0.4845],
        [ 1.5571,  1.8605, -2.0336,  0.5399]])


**Head 2**

In [8]:
head2 = self_attention(embeddings)
print("Head 2 Output :\n")
print(head2)

Head 2 Output :

tensor([[ 0.2931, -2.1267, -1.5792,  0.6474],
        [ 0.2803, -2.1179, -1.5845,  0.6322],
        [ 0.2863, -2.1177, -1.5805,  0.6383]])


**Concatenate Heads**

In [9]:
multi_head_output = torch.cat((head1 , head2) , dim = 1)
print("Concatenated Output :\n")
print(multi_head_output)

Concatenated Output :

tensor([[ 1.7690,  1.9718, -1.7850,  0.0694,  0.2931, -2.1267, -1.5792,  0.6474],
        [ 1.5779,  1.8138, -2.0367,  0.4845,  0.2803, -2.1179, -1.5845,  0.6322],
        [ 1.5571,  1.8605, -2.0336,  0.5399,  0.2863, -2.1177, -1.5805,  0.6383]])


**Check Shape**

In [10]:
print("Head 1 Shape : " , head1.shape)
print("Head 2 Shape : " , head2.shape)
print("Combined Shape : " , multi_head_output.shape)

Head 1 Shape :  torch.Size([3, 4])
Head 2 Shape :  torch.Size([3, 4])
Combined Shape :  torch.Size([3, 8])


**Output Projection**

In [11]:
projection = torch.randn(8 , 4)
final_output = multi_head_output @ projection
print("Projected Output :\n")
print(final_output)

Projected Output :

tensor([[ 0.1571, -7.8868,  7.3195,  7.2381],
        [-0.0425, -7.8366,  7.7322,  7.4673],
        [-0.1270, -7.7397,  7.8015,  7.5724]])


**Display Final Output**

In [12]:
for token , vector in zip(tokens , final_output) :
  print("=" * 40)
  print("Token : " , token)
  print("Output Vector : ")
  print(vector)

Token :  I
Output Vector : 
tensor([ 0.1571, -7.8868,  7.3195,  7.2381])
Token :  love
Output Vector : 
tensor([-0.0425, -7.8366,  7.7322,  7.4673])
Token :  Python
Output Vector : 
tensor([-0.1270, -7.7397,  7.8015,  7.5724])


**Compare Single vs Multi Head**

In [14]:
print("Single Head Shape : " , head1.shape)

print("Multi Head Shape : " , multi_head_output.shape)

print("Projected Shape : " , final_output.shape)

Single Head Shape :  torch.Size([3, 4])
Multi Head Shape :  torch.Size([3, 8])
Projected Shape :  torch.Size([3, 4])
