<a href="https://colab.research.google.com/github/RagaSandhiya05/LLM-From-Scratch/blob/main/09_Positional_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**POSITIONAL ENCODING**

**Import Libraries**

In [9]:
import torch
import math
torch.manual_seed(42)
print("PyTorch Version : " , torch.__version__)

PyTorch Version :  2.11.0+cpu


**Sample Tokens and Embeddings**

In [10]:
tokens = ["I" , "love" , "Python"]
embeddings = torch.tensor([
    [1.0 , 0.5 , 0.2 , 0.1] ,
    [0.8 , 1.0 , 0.4 , 0.3] ,
    [0.2 , 0.1 , 1.0 , 0.9]
])
print("Tokens : ")
print(tokens)

print("\nEmbeddings : ")
print(embeddings)

Tokens : 
['I', 'love', 'Python']

Embeddings : 
tensor([[1.0000, 0.5000, 0.2000, 0.1000],
        [0.8000, 1.0000, 0.4000, 0.3000],
        [0.2000, 0.1000, 1.0000, 0.9000]])


**Positional Encoding Function**

In [11]:
def positional_encoding(sequence_length , embedding_dim) :
  pe = torch.zeros(sequence_length , embedding_dim)
  for pos in range(sequence_length) :
    for i in range(0 , embedding_dim , 2) :
      pe[pos , i] = math.sin(pos / (10000 ** (i / embedding_dim)))
      if i + 1 < embedding_dim :
        pe[pos , i + 1] = math.cos(pos / (10000 ** (i / embedding_dim)))
  return pe

**Generate Positional Encoding**

In [12]:
sequence_length = len(tokens)
embedding_dim = embeddings.shape[1]
pe = positional_encoding(sequence_length , embedding_dim)
print("Positional Encoding : \n")
print(pe)

Positional Encoding : 

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0100,  0.9999],
        [ 0.9093, -0.4161,  0.0200,  0.9998]])


**Add Positional Encoding to Embeddings**

In [13]:
encoded_embeddings = embeddings + pe
print("Embeddings After Positional Encoding : \n")
print(encoded_embeddings)

Embeddings After Positional Encoding : 

tensor([[ 1.0000,  1.5000,  0.2000,  1.1000],
        [ 1.6415,  1.5403,  0.4100,  1.3000],
        [ 1.1093, -0.3161,  1.0200,  1.8998]])


**Compare Before and After**

In [14]:
for token , original , encoded in zip(tokens , embeddings , encoded_embeddings) :
  print("=" * 40)
  print("Token : " , token)
  print("\nOriginal Embedding : ")
  print(original)
  print("\nAfter Positional Encoding : ")
  print(encoded)

Token :  I

Original Embedding : 
tensor([1.0000, 0.5000, 0.2000, 0.1000])

After Positional Encoding : 
tensor([1.0000, 1.5000, 0.2000, 1.1000])
Token :  love

Original Embedding : 
tensor([0.8000, 1.0000, 0.4000, 0.3000])

After Positional Encoding : 
tensor([1.6415, 1.5403, 0.4100, 1.3000])
Token :  Python

Original Embedding : 
tensor([0.2000, 0.1000, 1.0000, 0.9000])

After Positional Encoding : 
tensor([ 1.1093, -0.3161,  1.0200,  1.8998])


**Token Positions**

In [16]:
print("Token Positions\n")
for position , token in enumerate(tokens) :
  print(f"Position {position} -> {token}")

Token Positions

Position 0 -> I
Position 1 -> love
Position 2 -> Python


**Why Positional Encoding ?**

In [17]:
sentence1 = ["Dog" , "bites" , "man"]
sentence2 = ["Man" , "bites" , "dog"]
print("Sentence 1 : " , sentence1)
print("Sentence 2 : " , sentence2)
print("\nBoth contain the same wordss.")
print("Positional Encoding helps the model to understand the different word order.")

Sentence 1 :  ['Dog', 'bites', 'man']
Sentence 2 :  ['Man', 'bites', 'dog']

Both contain the same wordss.
Positional Encoding helps the model to understand the different word order.


**Display Positional Encoding Matrix**

In [19]:
print("Positional Encoding Matrix\n")
for position , vector in  enumerate(pe) :
  print(f"Position {position} :")
  print(vector)
  print()

Positional Encoding Matrix

Position 0 :
tensor([0., 1., 0., 1.])

Position 1 :
tensor([0.8415, 0.5403, 0.0100, 0.9999])

Position 2 :
tensor([ 0.9093, -0.4161,  0.0200,  0.9998])

